# Generated by Django 2.2.6 on 2020-01-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('DevId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('DevName', models.CharField(max_length=20)),
                ('DevPhoneno', models.PositiveIntegerField()),
                ('DevEmail', models.EmailField(max_length=40)),
                ('Notes', models.TextField()),
            ],
        ),
    ]
