# Generated by Django 2.2.6 on 2020-01-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thecoding', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('AddressType', models.TextField()),
                ('Street', models.CharField(max_length=200)),
                ('LandMark', models.TextField()),
                ('Sector', models.TextField()),
                ('City', models.CharField(max_length=50)),
                ('PinCode', models.PositiveIntegerField()),
                ('State', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('blockId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('lifts', models.BooleanField()),
                ('floors', models.PositiveIntegerField()),
                ('unitavail', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Floorplan',
            fields=[
                ('PlanId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Configuration', models.TextField()),
                ('SuperArea', models.FloatField()),
                ('Loading', models.FloatField()),
                ('ServantRoom', models.BooleanField()),
                ('PoojaRoom', models.BooleanField()),
            ],
        ),
    ]
