# Generated by Django 2.2.6 on 2020-01-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thecoding', '0003_address_block_floorplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='LandMark',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='address',
            name='Sector',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='Configuration',
            field=models.CharField(max_length=10),
        ),
    ]
