# Generated by Django 2.2.6 on 2020-01-21 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thecoding', '0004_auto_20200121_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='developer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='thecoding.Developer'),
        ),
    ]
