# Generated by Django 2.2.6 on 2020-01-21 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thecoding', '0007_auto_20200121_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='thecoding.Project'),
        ),
        migrations.AddField(
            model_name='block',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecoding.Project'),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecoding.Block'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecoding.Developer'),
        ),
    ]
