# Generated by Django 2.2.6 on 2020-01-21 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thecoding', '0008_auto_20200121_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='thecoding.Address'),
            preserve_default=False,
        ),
    ]
