# Generated by Django 2.2.6 on 2020-01-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thecoding', '0013_auto_20200122_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='personId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
